# Generated by Django 4.0.1 on 2022-01-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_pub_date_question_дата публиации'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Дата публиации',
            new_name='PublicationDate',
        ),
    ]
