# Generated by Django 4.0.1 on 2022-01-29 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_question_text_question_questiontext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='QuestionText',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='PublicationDate',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
