# Generated by Django 4.0.1 on 2022-01-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_questiontext_question_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='pub_dateA',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_textA',
        ),
    ]
