# Generated by Django 4.0.1 on 2022-01-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_pub_date_question_pub_datea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dateA',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_textA',
            new_name='question_text',
        ),
    ]
